config/routes.rb
Rails.application.routes.draw do
  resources :musics

    root 'welcome#index'
    get '/start' => 'welcome#start_survey'
    get '/profile' => 'welcome#profile'
    get '/next_track' => 'musics#next_track'
    match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
    match 'auth/failure', to: redirect('/'), via: [:get, :post]
    match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/music.rb
class Music < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  # Try building a slug based on the following fields in
  # increasing order of specificity.
  def slug_candidates
    [
        :genre,
        [:genre, :artist],
        [:genre, :artist, :song_name],
    ]
  end

  def self.random_select_song
    song_name = Music.find_by_sql("select DISTINCT song_name,RANDOM() from musics ORDER BY RANDOM() LIMIT 1");
    Music.find_by_song_name(song_name.first.song_name)
  end

  def self.random_select user
    song_name = Music.find_by_sql("select DISTINCT song_name,RANDOM() from musics where SONG_NAME NOT IN('#{user.played_musics.map(&:song_name).uniq.join(",").gsub("'","''").to_s}') ORDER BY RANDOM() LIMIT 1");
    Music.find_by_song_name(song_name.first.song_name)
  end


end

app/models/played_music.rb
class PlayedMusic < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  has_and_belongs_to_many :users
  # Try building a slug based on the following fields in
  # increasing order of specificity.
  def slug_candidates
    [
        :genre,
        [:genre, :artist],
        [:genre, :artist, :song_name],
    ]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :played_musics

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.birthday = auth.extra.raw_info.birthday
      user.email = auth.extra.raw_info.email
      user.location = auth.info.location
      user.image = auth.info.image
      user.verified = auth.info.verified
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def signed_in?
    if current_user.nil?
      flash[:notice] = "Oops! looks like you are not logged in yet! please sign in"
      redirect_to root_path
    else
      true
    end
  end


  private
  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue
      session[:user_id] = nil
      redirect_to root_url
    end
  end
  helper_method :current_user
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :signed_in?

  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all
  end

  # GET /musics/1
  # GET /musics/1.json
  def show
      @music = Music.friendly.find(URI.unescape(params[:id]))
      # select random genre from all the music
      # create a client object with your app credentials
      client = Soundcloud.new(:client_id => 'd99d78670c7f1d537d0ae3d67a7be95c')
      @embed_info = client.get('/oembed', :url => @music.song_api,:auto_play => true)
  end
  def next_track
    @music = Music.find params[:music]
    if params[:status] == "love"
      played_music = PlayedMusic.find_or_initialize_by(:song_name => @music.song_name)
      played_music.song_api = @music.song_api
      played_music.love = true
      played_music.like = false
      played_music.hate = false
      played_music.not_kind = false
      played_music.genre = @music.genre
      played_music.artist = @music.artist
      current_user.played_musics << played_music
    elsif params[:status] == "kind"
      played_music = PlayedMusic.find_or_initialize_by(:song_name => @music.song_name)
      played_music.song_api = @music.song_api
      played_music.love = false
      played_music.like = false
      played_music.hate = false
      played_music.not_kind = true
      played_music.genre = @music.genre
      played_music.artist = @music.artist
      current_user.played_musics << played_music
    elsif params[:status] == "hate"
      played_music = PlayedMusic.find_or_initialize_by(:song_name => @music.song_name)
      played_music.song_api = @music.song_api
      played_music.love = false
      played_music.like = false
      played_music.hate = true
      played_music.not_kind = false
      played_music.genre = @music.genre
      played_music.artist = @music.artist
      current_user.played_musics << played_music
    elsif params[:status] == "like"
      played_music = PlayedMusic.find_or_initialize_by(:song_name => @music.song_name)
      played_music.song_api = @music.song_api
      played_music.love = false
      played_music.like = true
      played_music.hate = false
      played_music.not_kind = false
      played_music.genre = @music.genre
      played_music.artist = @music.artist
      current_user.played_musics << played_music
    end
      @next_music = Music.random_select_song
    if @next_music.nil?
      @next_music = Music.random_select(current_user)
      redirect_to music_path(@next_music.friendly_id)
    elsif current_user.played_musics.select(:song_name).include?(@next_music.song_name)
      @next_music = Music.random_select(current_user)
      redirect_to music_path(@next_music.friendly_id)
    elsif @next_music.id == @music.id
      @next_music = Music.random_select(current_user)
      redirect_to music_path(@next_music.friendly_id)
    else
      redirect_to music_path(@next_music.friendly_id)
    end
  end

  # GET /musics/new
  def new
    @music = Music.new
  end

  # GET /musics/1/edit
  def edit
  end

  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(music_params)

    respond_to do |format|
      if @music.save
        format.html { redirect_to @music, notice: 'Music was successfully created.' }
        format.json { render :show, status: :created, location: @music }
      else
        format.html { render :new }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musics/1
  # PATCH/PUT /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to @music, notice: 'Music was successfully updated.' }
        format.json { render :show, status: :ok, location: @music }
      else
        format.html { render :edit }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url, notice: 'Music was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.random_select
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def music_params
      params.require(:music).permit(:artist, :song_name, :song_api, :genre, :slug)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :signed_in? ,:only => [:start_survey,:profile]
  def index
  end

  def start_survey
    @music = Music.random_select_song
    redirect_to music_path(@music.friendly_id)
  end

  def profile
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DiscoverYourTasteApp</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>
<div class="navbar navbar-default visible-xs" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle Navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
</div>
<div class="container-fluid">
  <div class="row-fluid">

    <div class="navbar-collapse collapse navbar-right " id="bs-example-navbar-collapse-1">
      <ul class="nav nav-pills">
        <li role="presentation" ><a href="/">Home</a></li>
        <li role="presentation" ><a href="#">PlayLists</a></li>
        <li role="presentation" ><a href="/profile">Profile</a></li>
      </ul>
    </div>
  </div>
  <div id="user-widget" class="navbar-left" style="position: relative;top: 1.6em;left:0em">
    <% if !current_user.nil? %>
        Welcome <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out",:class => "btn btn-info" %>
    <% else %>
        <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in",:class => "btn btn-info" %>
    <% end %>
  </div>
  <div class="row" style="margin-top: 4em">
    <% flash.each do |key, value| %>
        <div class="alert alert-info fade in">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <%= value %>
        </div>
    <% end %>
  </div>
  <%= yield %>
</div>

</body>
</html>

app/views/musics/_form.html.erb
<%= form_for(@music) do |f| %>
  <% if @music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% @music.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :song_name %><br>
    <%= f.text_field :song_name %>
  </div>
  <div class="field">
    <%= f.label :song_api %><br>
    <%= f.text_field :song_api %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musics/edit.html.erb
<h1>Editing Music</h1>

<%= render 'form' %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Musics</h1>

<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Song name</th>
      <th>Song api</th>
      <th>Genre</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @musics.each do |music| %>
      <tr>
        <td><%= music.artist %></td>
        <td><%= music.song_name %></td>
        <td><%= music.song_api %></td>
        <td><%= music.genre %></td>
        <td><%= music.slug %></td>
        <td><%= link_to 'Show', music %></td>
        <td><%= link_to 'Edit', edit_music_path(music) %></td>
        <td><%= link_to 'Destroy', music, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Music', new_music_path %>

app/views/musics/new.html.erb
<h1>New Music</h1>

<%= render 'form' %>

<%= link_to 'Back', musics_path %>

app/views/musics/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="soundcloud">
        <%= @embed_info['html'].html_safe %>
    </div>
    <h1>Click play and tell us how do you like the song <%= @music.artist %></h1>
    <div class="button">
        <%= link_to "<i class='fa fa-heartbeat fa-lg'></i>Love IT!".html_safe, next_track_path(music: @music.id, status: 'love'),:class =>"btn btn-success btn-lg" %>
        <%= link_to "<i class='fa fa-times fa-lg'></i> Nah! Not my Kind".html_safe, next_track_path(music: @music.id, status: 'kind'),:class =>"btn btn-warning btn-lg" %>
        <%= link_to "<i class='fa fa-thumbs-up fa-lg'></i>I Like IT!".html_safe, next_track_path(music: @music.id, status: 'like'),:class =>"btn btn-info btn-lg" %>
        <%= link_to "<i class='fa fa-ambulance fa-lg'></i>This is Horrible!".html_safe, next_track_path(music: @music.id, status: 'hate'),:class =>"btn btn-danger btn-lg" %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="row" style="margin-top: 3em">
  <div class="col-md-6 index">
    <i class="fa fa-music fa-5x"></i><h1 class="share "> Discover Music </h1>
    <i class="fa fa-heart fa-5x"></i><h1 class="share "> You Might Love!</h1>
    <i class="fa fa-list-alt fa-5x"></i><h1 class="share "> Create PlayLists </h1>
    <i class="fa fa-users fa-5x"></i><h1 class="share "> Share With Friends</h1>
  </div>
  <div class="col-md-4 para">
    <a href="/start" style="padding: 1em 1em 1em 1em;margin-left: 1em" type="button" class="btn btn-success btn-success_welcome btn-lg" aria-label="Left Align">
      <span class="glyphicon glyphicon-sunglasses" aria-hidden="true"></span> Discover Music!
    </a>

    <p class="lead"> Just Experience a Survey and know what kind of music you might love</p>
    <p class="lead"> Its pretty simple, we are going to play some music with every question And</p>
    <p class="lead"> All you have of do is say <em style="color: #ffd801;">"love It"</em> or <em style="color: #000000;">"Nah! not my kind"</em> or <em style="color: #33f73c;">"Like It"</em> or say <em style="color: #4803a5;">"Horrible!</em>"</p>
  </div>
</div>

app/views/welcome/profile.html.erb
<div class="row" style="margin-top: 3em">
  <div class="col-md-6 col-md-offset-3">
    <h1> Name: <%= @user.name %></h1>
    <h1> Recently Played songs: </h1>
    <% @user.played_musics.select(:song_name,:slug).distinct.to_a.each do |m|%>
        <li><%= link_to m.song_name, "/musics/#{m.slug}" %></li>
    <% end %>

  </div>
</div>